name: Deploy production

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "develop" ]

jobs:
  build:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: trungnt321/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          post: ${{ secrets.PORT }}
          script: |
            pwd
            cd /var/www/html/apiEvent
            pwd
            git pull
            php artisan cache:clear
            php artisan route:cache
            composer install
            php artisan migrate
            php artisan optimize:clear
            whoami && pwd
